config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # Send everything to React through the homes#index route
  root 'homes#index'
  get '/home',               to: 'homes#index'
  get '/about',               to: 'homes#index'
  get '/news',                to: 'homes#index'
  get '/log_in',              to: 'homes#index'
  get '/sign_up',             to: 'homes#index'
  get '/order',               to: 'homes#index'
  get '/order_confirmation',  to: 'homes#index'
  
  resources :users, only: [:index]
  resources :addresses, only: [:create]
  resources :promotions, only: [:index]

  namespace :admin do
    resources :users, only: [:index, :show]
    resources :guests, only: [:show]
    resources :promotions
  end
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  validates :name, :url, presence: true
  validates :active, inclusion: { in: [true, false]}

  before_save :reset_active

  private
  def reset_active
    if self.active
      Promotion.update_all(active: false)
    end
  end
end

app/controllers/admin/promotions_controller.rb
class Admin::PromotionsController < Admin::AdminController
  def index
    @promotions = Promotion.all
  end

  def new
    @promotion = Promotion.new
  end

  def create
    @promotion = Promotion.new(promotions_params)

    if @promotion.save
      redirect_to admin_promotions_path
    else
      @error = @promotion.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @promotion = Promotion.find(params[:id])
    render :new
  end

  def update
    @promotion = Promotion.find(params[:id])

    if @promotion.update(promotions_params)
      redirect_to admin_promotions_path
    else
      @error = @promotion.errors.full_messages.to_sentence
      render :new
    end
  end

  def destroy
    @promotion = Promotion.find(params[:id])
    @promotion.destroy
    redirect_to admin_promotions_path
  end

  private
  def promotions_params
    params.require(:promotion).permit(:name, :url, :description, :active)
  end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  # returns the active promotion
  def index
    @promotion = Promotion.find_by(active: true)
    promo_info = nil
    if @promotion
      promo_info = {
        name: @promotion.name,
        url: @promotion.url,
        description: @promotion.description
      }
    end

    render json: promo_info
  end
end

app/views/admin/promotions/index.html.erb
<h1>Promotions</h1>
<%= link_to "Add New Promotion", new_admin_promotion_url, class: "new-link" %>
<div>
  <table>
    <thead>
      <tr>
        <th>Name (callout button text)</th>
        <th>URL (use '/order' for internal order form)</th>
        <th>Description (for internal order form, otherwise leave blank)</th>
        <th>Active</th>
        <th>Set Active</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @promotions.each do |promo| %>
        <tr>
          <td><%= link_to promo.name, edit_admin_promotion_path(promo) %></td>
          <td><%= promo.url %></td>
          <td><%= promo.description %></td>
          <td><%= promo.active %></td>
          <td><%= button_to "Toggle Active", [:admin, promo], method: "patch", params: {promotion: {active: true}}, class: "no-margin" %></td>
          <td><%= link_to "Delete Promotion", [:admin, promo], method: "delete", confirm: "Are you sure?" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/promotions/new.html.erb
<h1>New Promotion</h1>
<% if @error %>
  <p class="error"><%= @error %></p>
<% end %>
<%= form_with model: [:admin, @promotion] do |form| %>
  <label>Name (callout button text)
    <%= form.text_field :name %>
  </label>
  <label>URL (use '/order' for internal order form)
    <%= form.text_field :url %>
  </label>
  <label>Description (for internal order form, otherwise leave blank)<br/>
    <%= form.text_area :description %>
  </label><br/>
  <label class="checkbox-label">Set as Active Promotion
    <%= form.check_box :active %>
  </label>
  <br/>
  <%= form.submit %>
<% end %>