config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # Send everything to React through the homes#index route
  root 'homes#index'
  get '/home',               to: 'homes#index'
  get '/about',               to: 'homes#index'
  get '/news',                to: 'homes#index'
  get '/log_in',              to: 'homes#index'
  get '/sign_up',             to: 'homes#index'
  get '/order',               to: 'homes#index'
  get '/order_confirmation',  to: 'homes#index'
  
  resources :users, only: [:index]
  resources :addresses, only: [:create]
  resources :promotions, only: [:index]

  namespace :admin do
    resources :users, only: [:index, :show]
    resources :guests, only: [:show]
    resources :promotions
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ramshackle Admin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div id="admin-topbar">
      <p>Ramshackle Admin</p>
      <%= link_to "Users", admin_users_path %>
      <%= link_to "Promotions", admin_promotions_path %>
      <%= link_to 'Application Home', root_path %>
    </div>
    <div id="admin-content">
      <%= yield %>
    <dv>
    <%- if Rails.env.development? || Rails.env.test? -%>
      <%= javascript_tag do %>
        window.railsEnv = '<%= Rails.env %>'
      <%- end -%>
    <%- end -%>
    <%= yield :extra_footer %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ramshackle Farm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
    <%- if Rails.env.development? || Rails.env.test? -%>
      <%= javascript_tag do %>
        window.railsEnv = '<%= Rails.env %>'
      <%- end -%>
    <%- end -%>
    <%= javascript_pack_tag 'ReactApp' %>
    <%= yield :extra_footer %>
  </body>
</html>